apiVersion: 1.0.0
kind: Component
metadata:
  name: product-service
  description: A sample rest service
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: retheesh
